### ISSUE TITLE
getting error on - 'pip install django-phone-login'

### ISSUE THREAD

**Issue by anmolakhilesh** [wejhink/django-phone-login#10]
`Collecting django-phone-login
  Using cached django-phone-login-1.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    warning: pypandoc module not found, could not convert Markdown to RST
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/78/721n2gxn0sng0v48cmx1jsc00000gn/T/pip-build-TYVu1I/django-phone-login/setup.py", line 55, in <module>
        REQUIREMENTS = [i.strip() for i in open("requirements/requirements-mandatory.txt").readlines()]
    IOError: [Errno 2] No such file or directory: 'requirements/requirements-mandatory.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/78/721n2gxn0sng0v48cmx1jsc00000gn/T/pip-build-TYVu1I/django-phone-login/`

![issue](https://user-images.githubusercontent.com/16012094/28265320-c709011e-6b0c-11e7-977a-ce570725fa6f.jpg)

**Comment by iraycd** [comment]
Which is your setuptools version? Please give me an output of
```
pip list
```
Try to upgrade setuptools
```
pip install -U setuptools pip
```
