### ISSUE TITLE
PhoneToken matching query does not exist.

### ISSUE THREAD

**Issue by Mbaqban** [wejhink/django-phone-login#17]
DoesNotExist at /admin/login/
PhoneToken matching query does not exist.
Request Method:  POST
Request URL:  http://127.0.0.1:8000/admin/login/?next=/admin/
Django Version:  2.0.7
Exception Type:  DoesNotExist
Exception Value:  
PhoneToken matching query does not exist.
Exception Location:  /home/mohamad/project02/vir/lib/python3.7/site-packages/django/db/models/query.py in get, line 403
Python Executable:  /home/mohamad/project02/vir/bin/python
Python Version:  3.7.0
Python Path:  
['/home/mohamad/project02/zendegino_backend',
 '/usr/lib/python37.zip',
 '/usr/lib/python3.7',
 '/usr/lib/python3.7/lib-dynload',
 '/home/mohamad/project02/vir/lib/python3.7/site-packages']
Server time:  Sun, 12 Aug 2018 18:36:37 +0000

**Comment by iraycd** [comment]
Any PR is encouraged.

**Comment by iraycd** [comment]
@anmolakhilesh Can you take care of this?

**Comment by Mbaqban** [comment]
ok shod

**Comment by alican** [comment]
Whats the solution for this issue? Are any fixes provided? I have still this issue.

**Comment by mxmaher** [comment]
The solution for this is for the auth backend to return None on not finding the phone token not re-raise the exception 

as the django docs specify:
> Either way, authenticate() should check the credentials it gets and return a user object that matches those credentials if the credentials are valid. If they’re not valid, it should return None.
[refrence](https://docs.djangoproject.com/en/3.0/topics/auth/customizing/#writing-an-authentication-backend)

**Comment by omideus** [comment]
> 
> 
> ok shod

Can you please explain your solution to this issue?!

**Comment by Mbaqban** [comment]
yes its beacuse of django priority of "
`AUTHENTICATION_BACKENDS`"


just re order  AUTHENTICATION_BACKENDS like this 

```python
AUTHENTICATION_BACKENDS = [

    'django.contrib.auth.backends.ModelBackend',
    'phone_login.backends.phone_backend.PhoneBackend',
]
```

in your settings.py

and if you want know more 

search about priority AUTHENTICATION_BACKENDS

**Comment by Mbaqban** [comment]
> > ok shod
> 
> Can you please explain your solution to this issue?!


yes its beacuse of django priority of "
AUTHENTICATION_BACKENDS"

just re order AUTHENTICATION_BACKENDS like this

AUTHENTICATION_BACKENDS = [

    'django.contrib.auth.backends.ModelBackend',
    'phone_login.backends.phone_backend.PhoneBackend',
]
in your settings.py

and if you want know more

search about priority AUTHENTICATION_BACKENDS
